version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: hackathon_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hackathon_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./backend:/app

volumes:
  redis_data: